### ISSUE TITLE
How to debug generated packages

### ISSUE THREAD

**Issue by masterkorp** [hogliux/bomutils#18]
Hello,

First of all congratulations on this tool.

After generating my first package. I am failing to install it with the ``installer`` tool on mac osx.
```
installer: Error the package path specified was invalid:
```
Using ``-verbose`` does not really help either.

I followed the [tutorial](http://hogliux.github.io/bomutils/tutorial.html) and checked the steps carefully.

How can I get more information to help me narrow down where the problem is ?

--
Regards,
Alfredo Palhares

**Comment by hogliux** [comment]
Hi Alfredo,

From my experience, it's very difficult to debug installer packages on OS X
and the slightest mistake will make OS X not accept the package (for
example by setting the wrong compression method with xar: it needs to be
'none'). The logs are painfully unhelpful.

Is it possible that you send me a stripped down version of your installer?
I can then compare it to the installers that I have generated and maybe
help you find the problem a bit quicker. Did you try installing it by
simply double-clicking the installer package? I'm not sure how the command
line installer tool handles meta-packages.

Cheers,

Fabian

**Comment by masterkorp** [comment]
Hello,

What parts of the installer would be interested in ?

Installation by double clicking gives me the message.
```
The operation couldn't be completed.
(com.apple.installer.pagecontroller error -1.)
Couldn't open "my-intaller.pkg"
```

**Comment by hogliux** [comment]
Can you just send me the whole packge (.pkg file)?

**Comment by masterkorp** [comment]
Hello,

I sent on an example stripped package directly to your email account.

**Comment by hogliux** [comment]
There were several mistakes that I found in your package. 

1. You need to put the ReadMe, License and Welcome files into the en.lproj subfolder of the Resources folder. See Fig. 2 of tutorial
2. Your Distribution file has an extra tab at the beginning and this makes the xml file invalid. You probably copied the code from the tutorial page which had the extra tab in code listing. I've updated the tutorial with commit e3e9b01
3. The system version check in your Distribution file is deprecated and will always evaluate to false on newer systems. Again, this was wrong in the tutorial and I've fixed this with e3e9b01. See updated tutorial for the correct way to check the system version.

Your installer is still failing and I am investigating. But it should be much easier to debug now.

**Comment by hogliux** [comment]
From the install logs it looks like the postinstall script is causing trouble. Try removing it!

**Comment by hogliux** [comment]
I've removed the installer script and your package works for me now (OS X Yosemite). The installer script you provided was apparently copy&pasted from my tutorial but it was missing half of the last line. I don't know what happened there.
