### ISSUE TITLE
lsbom: BOM file from iOS OTA Update not readable

### ISSUE THREAD

**Issue by HellGL** [hogliux/bomutils#21]
Hi,
at the weekend I tried to list the contents of the pre.bom and post.bom of a iOS OTA update file. lsbom just says nothing. I tracked the problem down to line 271:
` if (name == "Paths") {`
For whatever reason this statement is always false, even if name is indeed "Paths". If I rewrite the statement to 
` if (strstr(name.c_str(),"Paths") == 0) {`
it works and shows the contents of the BOM file. I know this is not a fix, but at least it works for my particular problem.

Regards,
HellG

**Comment by scollinson** [comment]
Have had the same problem and this fix works for me.

**Comment by hogliux** [comment]
Fixed with commit 704739ca4eb6cd434f025481dafde652c2e1ba79
